### ISSUE TITLE
Problem with JQuery 1.9.1 and Jtable when trying to load a data

### ISSUE THREAD

**Issue by ehuggins** [hikalkan/jtable#2103]
I have a problem trying to load a jtable. I have already verified what is sent from a web service and no field is empty or null. The error that I get through the console is as follows: Uncaught TypeError: Can not read property 'length' of undefined at Function.each (http: // localhost: 19451 / assets / plugins / jQuery / 1.9.1 / jquery. min.js: 3: 5102) at anonymous function. (anonymous function) ._ addRecordsToTable. I'm working with the version of JQuery 1.9.1

**Comment by ehuggins** [comment]
This is the error:
Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.each (http://localhost:19451/assets/plugins/jQuery/1.9.1/jquery.min.js:3:5102)
    at e.(anonymous function).(anonymous function)._addRecordsToTable (http://localhost:19451/assets/plugins/jtable/jtable.min.js?v=61476:399:6)
    at e.(anonymous function).(anonymous function)._addRecordsToTable (http://localhost:19451/assets/plugins/jQueryUI/jquery-ui-1.9.2.min.js?v=41599:5:5392)
    at c (http://localhost:19451/assets/plugins/jtable/jtable.min.js?v=61476:353:85)
    at Object.success (http://localhost:19451/assets/plugins/jtable/jtable.min.js?v=61476:371:6)
    at Object.a.success (http://localhost:19451/assets/plugins/jtable/aspNetPageMethods.min.js?v=28274:11:68)
    at c (http://localhost:19451/assets/plugins/jQuery/1.9.1/jquery.min.js:3:7857)
    at Object.fireWith [as resolveWith] (http://localhost:19451/assets/plugins/jQuery/1.9.1/jquery.min.js:3:8658)
    at k (http://localhost:19451/assets/plugins/jQuery/1.9.1/jquery.min.js:5:14015)
    at XMLHttpRequest.r (http://localhost:19451/assets/plugins/jQuery/1.9.1/jquery.min.js:5:18226)
